DevelopersForum/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevelopersForum.Models
{
    public class Post
    {
        [Key]
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime Created { get; set; }

        public string Id { get; set; }
        public virtual ApplicationUsers ApplicationUsers { get; set; }
        public int ForumId { get; set; }
        public virtual Forum Forum { get; set; }

        public virtual IEnumerable<PostReply> Replies { get; set; }
    }
}

DevelopersForum/ViewModels/Post/NewPostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevelopersForum.ViewModels.Post
{
    public class NewPostModel
    {
        public string ForumName { get; set; }
        public int ForumId { get; set; }
        public string AuthorName { get; set; }
        public string ForumImageUrl { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}

DevelopersForum/ViewModels/Post/PostIndexModel.cs
using System;
using System.Collections.Generic;

namespace DevelopersForum.ViewModels
{
    public class PostIndexModel
    {
        public int Id { get; set; }
        public string  Title { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }
        public string AuthorImageUrl { get; set; }
        public int AuthorRating { get; set; }
        public DateTime Created { get; set; }
        public string PostContent { get; set; }
        public bool IsAuthorAdmin { get; set; }

        public int ForumId { get; set; }
        public string ForumName { get; set; }

        public IEnumerable<PostReplyModel> Replies { get; set; }
    }
}

DevelopersForum/ViewModels/Post/PostListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevelopersForum.ViewModels
{
    public class PostListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating { get; set; }
        public string AuthorId { get; set; }
        public string DatePosted { get; set; }

        public ForumListingModel Forum { get; set; }

        public int RepliesCount { get; set; }
    }
}

DevelopersForum/Controllers/PostController.cs
using DevelopersForum.Interfaces;
using DevelopersForum.Models;
using DevelopersForum.Models.Interfaces;
using DevelopersForum.ViewModels;
using DevelopersForum.ViewModels.Post;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevelopersForum.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly IForumService _forumService;
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly IApplicationUser _userService;

        public PostController(IPostService postService,
            IForumService forumService,
            UserManager<ApplicationUsers> userManager,
            IApplicationUser userService)
        {
            _postService = postService;
            _forumService = forumService;
            _userManager = userManager;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var post = _postService.GetById(id);
            var replies = BuildPostReplies(post.Replies);

            var model = new PostIndexModel
            {
                Id = post.PostId,
                Title = post.Title,
                AuthorId = post.ApplicationUsers.Id,
                AuthorName = post.ApplicationUsers.UserName,
                AuthorImageUrl = post.ApplicationUsers.ProfileImageUrl,
                AuthorRating = post.ApplicationUsers.Rating,
                Created = post.Created,
                PostContent = post.Content,
                Replies = replies, 
                ForumId = post.Forum.ForumId,
                ForumName = post.Forum.Title,
                IsAuthorAdmin = IsAuthorAdmin(post.ApplicationUsers)
            };

            return View(model);
        }

        [Authorize]
        public IActionResult Create(int id)
        {
            var forum = _forumService.GetById(id);

            var model = new NewPostModel
            {
                ForumName = forum.Title,
                ForumId = forum.ForumId,
                ForumImageUrl = forum.ImageUrl,
                AuthorName = User.Identity.Name
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddPost(NewPostModel model)
        {
            var userId = _userManager.GetUserId(User);
            var user = _userManager.FindByIdAsync(userId).Result;
            var post = BuildPost(model, user);

            await _postService.Add(post);

            await _userService.UpdateUserRating(userId, typeof(Post));

            return RedirectToAction("Index", "Post", new { id = post.PostId });
        }

        private bool IsAuthorAdmin(ApplicationUsers applicationUsers)
        {
            return _userManager.GetRolesAsync(applicationUsers).Result.Contains("Admin");
        }

        private Post BuildPost(NewPostModel model, ApplicationUsers user)
        {
            var forum = _forumService.GetById(model.ForumId);
            return new Post
            {
                Title = model.Title,
                Content = model.Content,
                Created = DateTime.Now,
                ApplicationUsers = user,
                Forum = forum
            };
        }

        private IEnumerable<PostReplyModel> BuildPostReplies(IEnumerable<PostReply> replies)
        {
            return replies.Select(reply => new PostReplyModel
            {
                Id = reply.PostReplyId,
                AuthorName = reply.ApplicationUsers.UserName,
                AuthorId = reply.ApplicationUsers.Id,
                AuthorImageUrl = reply.ApplicationUsers.ProfileImageUrl,
                AuthorRating = reply.ApplicationUsers.Rating,
                Created = reply.Created,
                ReplyContent = reply.Content,
                IsAuthorAdmin = IsAuthorAdmin(reply.ApplicationUsers)
            });
        }
    }
}

DevelopersForum/Controllers/ProfileController.cs
using DevelopersForum.Interfaces;
using DevelopersForum.Models;
using DevelopersForum.ViewModels.Profile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace DevelopersForum.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly IApplicationUser _userService;
        private readonly IUpload _uploadService;

        public ProfileController(UserManager<ApplicationUsers> userManager, 
            IApplicationUser userService,
            IUpload uploadService)
        {
            _userManager = userManager;
            _userService = userService;
            _uploadService = uploadService;
        }

        public IActionResult Detail(string id)
        {
            var user = _userService.GetById(id);
            var userRoles = _userManager.GetRolesAsync(user).Result;

            var model = new ProfileModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRating = user.Rating.ToString(),
                Email = user.Email,
                ProfileImageUrl = user.ProfileImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin")
            };
            return View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> UploadProfileImage(IFormFile file)
        //{
        //    var userId =  _userManager.GetUserId(User);

        //    // Connect to an Azure Storage Account Container
        //    var connectionString = _configuration.GetConnectionString("AzureStorageAccount");
        //    // Get Blob Container
        //    var container = _uploadService.GetBlobContainer(connectionString, "profile-images");
        //    // Parse the content disposition response header
        //    var contentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);
        //    // Grab the filename
        //    var filename = contentDisposition.FileName.Trim("""");
        //    // Get a reference to a block blob
        //    var blockBlob = container.GetBlobReference(fileName);
        //    // On that block blob, upload our file <...file uploaded to the cloud
        //    await blockBlob.UploadFormStreamAsync(file.OpenReadStream());
        //    // Set the user's profile image to the URI
        //    await _userService.SetProfileImage(userId, blockBlob.Uri);
        //    // Redirect to the user's profile page
        //    return RedirectToAction("Detail", "Profile", new { id = userId });
        //}

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _userService.GetAll()
                .OrderByDescending(user => user.Rating)
                 .Select(user => new ProfileModel
                 {
                     UserName = user.UserName,
                     Email = user.Email,
                     ProfileImageUrl = user.ProfileImageUrl,
                     MemberSince = user.MemberSince,
                     UserRating = user.Rating.ToString()
                 });

            var model = new ProfileListModel
            {
                Profiles = users
            };

            return View(model);
        }
    }
}

DevelopersForum/Controllers/ReplyController.cs
using DevelopersForum.Interfaces;
using DevelopersForum.Models;
using DevelopersForum.Models.Interfaces;
using DevelopersForum.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevelopersForum.Controllers
{
    [Authorize]
    public class ReplyController : Controller
    {
        private readonly IPostService _postService;
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly IApplicationUser _userService;

        public ReplyController(IPostService postService,
            UserManager<ApplicationUsers> userManager,
            IApplicationUser userService)
        {
            _postService = postService;
            _userManager = userManager;
            _userService = userService;
        }

        public async Task<IActionResult> Create(int id)
        {
            var post = _postService.GetById(id);
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            var model = new PostReplyModel
            {
                PostContent = post.Content,
                PostTitle = post.Title,
                PostId = post.PostId,

                AuthorId = user.Id,
                AuthorName = User.Identity.Name,
                AuthorImageUrl = user.ProfileImageUrl,
                AuthorRating = user.Rating,
                IsAuthorAdmin = User.IsInRole("Admin"),

                ForumId = post.Forum.ForumId,
                ForumName = post.Forum.Title,
                ForumImageUrl = post.Forum.ImageUrl,

                Created = DateTime.Now
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddReply(PostReplyModel model)
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);

            var reply = BuildReply(model, user);

            await _postService.AddReply(reply);
            await _userService.UpdateUserRating(userId, typeof(PostReply));

            return RedirectToAction("Index", "Post", new { id = model.PostId });
        }

        private PostReply BuildReply(PostReplyModel model, ApplicationUsers user)
        {
            var post = _postService.GetById(model.PostId);

            return new PostReply
            {
                Post = post,
                Content = model.ReplyContent,
                Created = DateTime.Now,
                ApplicationUsers = user
            };
        }
    }
}

DevelopersForum/Views/Post/Create.cshtml
@model DevelopersForum.ViewModels.Post.NewPostModel

<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading">
            New Post | @Model.ForumName
            <div class="forumLogo" style="background-image: url(@Model.ForumImageUrl)"></div>
            <span id="headingBtn">
                <a asp-controller="Forum"
                   asp-action="Topic"
                   asp-route-id="@Model.ForumId"
                   class="btn btn-secondary">
                    Back to @Model.ForumName
                </a>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="createPostSection col-md-12">
            <div class="authorBlock" style="padding: 18px; border: 1px dashed #00AFCF; margin-bottom: 8px;">
                You're submitting this post as <strong>@Model.AuthorName</strong>
            </div>
            <form asp-action="AddPost" method="post" id="addPostForm">
                <div class="form-group">
                    <label asp-for="Title"><strong>Title</strong></label>
                    <input asp-for="Title" class="form-control" placeholder="Post title" />
                </div>
                <div class="form-group">
                    <label asp-for="Content"><strong>Content</strong></label>
                    <textarea asp-for="Content" class="form-control" rows="20" placeholder="Post content..."></textarea>
                </div>
                <button type="submit" id="submitPostBtn" class="btn btn-submitPost">
                    Submit Post
                </button>
                <input asp-for="ForumId" type="hidden" />
            </form>
        </div>
    </div>
</div>

DevelopersForum/Views/Post/Index.cshtml
@model  DevelopersForum.ViewModels.PostIndexModel


    <div class="container body-content">
        <div class="row postHeader">
            <div class="postHeading">
                <span class="postIndexTitle">
                    @Model.Title
                </span>
                <span id="headingBtn">
                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@Model.ForumId" class="btn btn-secondary">
                    Back to @Model.ForumName
                     </a>
                </span>
            </div>
        </div>

        <div class="row" id="postIndexContent">
            <div class="col-md-3 postAuthorContainer">
                <div class="postAuthorImage" style="background-image: url(@Model.AuthorImageUrl);"></div>
                <a asp-controller="Profile" asp-action="Detail" asp-route-id="@Model.AuthorId">
                    @Model.AuthorName
                </a>
                <span class="postData">@Model.Created</span>
                @if (Model.IsAuthorAdmin)
                {
                    <span class="isAdmin smaller" style="display: inline-block; padding: 3px;background-color: #FFEB38; color:#000;font-family:'Roboto Mono';">Admin</span>
                }
            </div>
            <div class="col-md-9 postContentContainer">
                <div class="postContent">
                    @Html.Raw(Model.PostContent)
                </div>
            </div>
        </div>
        <div class="row" id="replyDivider"></div>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="row" style="background-color: #3F51B5; padding: 8px;">
                <span>
                    <a asp-controller="Reply" asp-action="Create" asp-route-id="@Model.Id" class="btn btn-newReply">
                        Post Reply
                    </a>
                </span>
            </div>
        }

        @if (Model.Replies.Any())
        {
            foreach (var reply in Model.Replies)
            {
                <div class="row replyContent" style="display: table;background-color: #fff;border-bottom: 1px solid #aaa; width:1110px;">
                    <div class="col-md-3 replyAuthorContainer">
                        <div class="postAuthorImage" style="background-image: url(@reply.AuthorImageUrl)"></div>
                        <a asp-controller="Profile" asp-action="Detail" asp-route-id="@reply.AuthorId">
                            @reply.AuthorName
                        </a>
                        @if (reply.IsAuthorAdmin)
                        {
                            <br />
                            <div class="isAdmin smaller" style="display: inline-block; padding: 3px;background-color: #FFEB38; color:#000;font-family:'Roboto Mono';">Admin</div>
                        }
                        <br />
                        <span class="postData">@reply.Created</span>
                    </div>
                    <div class="col-md-9 replyContentContainer">
                        <div class="replyContent">
                            @Html.Raw(reply.ReplyContent)
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="noPosts">
                <h3>
                    There are no replies to this post. <br />
                </h3>
            </div>
        }
</div>