DevelopersForum/ViewModels/Home/HomeIndexModel.cs
using System.Collections.Generic;

namespace DevelopersForum.ViewModels.Home
{
    public class HomeIndexModel
    {
        public IEnumerable<PostListingModel> LatestPosts { get; set; }
        public string SearchQuery { get; set; }
    }
}

DevelopersForum/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DevelopersForum.Models;
using DevelopersForum.ViewModels.Home;
using DevelopersForum.Models.Interfaces;
using System.Linq;
using DevelopersForum.ViewModels;

namespace DevelopersForum.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService _postService;

        public HomeController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult Index()
        {
            var model = BuildHomeIndexModel();
            return View(model);
        }

        private HomeIndexModel BuildHomeIndexModel()
        {
            var latestPosts = _postService.GetLatestPosts(10); 

            var posts = latestPosts.Select(post => new PostListingModel
            {
                Id = post.PostId,
                Title = post.Title,
                AuthorName = post.ApplicationUsers.UserName,
                AuthorId = post.ApplicationUsers.Id,
                AuthorRating = post.ApplicationUsers.Rating,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = GetForumListingForPost(post)
            });

            return new HomeIndexModel
            {
                LatestPosts = posts,
                SearchQuery = ""
            };
        }

        private ForumListingModel GetForumListingForPost(Post post)
        {
            var forum = post.Forum;

            return new ForumListingModel
            {
                Id = forum.ForumId,
                Name = forum.Title,
                ImageUrl = forum.ImageUrl
            };
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevelopersForum/Controllers/ProfileController.cs
using DevelopersForum.Interfaces;
using DevelopersForum.Models;
using DevelopersForum.ViewModels.Profile;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace DevelopersForum.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUsers> _userManager;
        private readonly IApplicationUser _userService;
        private readonly IUpload _uploadService;

        public ProfileController(UserManager<ApplicationUsers> userManager, 
            IApplicationUser userService,
            IUpload uploadService)
        {
            _userManager = userManager;
            _userService = userService;
            _uploadService = uploadService;
        }

        public IActionResult Detail(string id)
        {
            var user = _userService.GetById(id);
            var userRoles = _userManager.GetRolesAsync(user).Result;

            var model = new ProfileModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRating = user.Rating.ToString(),
                Email = user.Email,
                ProfileImageUrl = user.ProfileImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin")
            };
            return View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> UploadProfileImage(IFormFile file)
        //{
        //    var userId =  _userManager.GetUserId(User);

        //    // Connect to an Azure Storage Account Container
        //    var connectionString = _configuration.GetConnectionString("AzureStorageAccount");
        //    // Get Blob Container
        //    var container = _uploadService.GetBlobContainer(connectionString, "profile-images");
        //    // Parse the content disposition response header
        //    var contentDisposition = ContentDispositionHeaderValue.Parse(file.ContentDisposition);
        //    // Grab the filename
        //    var filename = contentDisposition.FileName.Trim("""");
        //    // Get a reference to a block blob
        //    var blockBlob = container.GetBlobReference(fileName);
        //    // On that block blob, upload our file <...file uploaded to the cloud
        //    await blockBlob.UploadFormStreamAsync(file.OpenReadStream());
        //    // Set the user's profile image to the URI
        //    await _userService.SetProfileImage(userId, blockBlob.Uri);
        //    // Redirect to the user's profile page
        //    return RedirectToAction("Detail", "Profile", new { id = userId });
        //}

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _userService.GetAll()
                .OrderByDescending(user => user.Rating)
                 .Select(user => new ProfileModel
                 {
                     UserName = user.UserName,
                     Email = user.Email,
                     ProfileImageUrl = user.ProfileImageUrl,
                     MemberSince = user.MemberSince,
                     UserRating = user.Rating.ToString()
                 });

            var model = new ProfileListModel
            {
                Profiles = users
            };

            return View(model);
        }
    }
}

DevelopersForum/Controllers/SearchController.cs
using DevelopersForum.Models;
using DevelopersForum.Models.Interfaces;
using DevelopersForum.ViewModels;
using DevelopersForum.ViewModels.Search;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace DevelopersForum.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPostService _postService;
         
        public SearchController(IPostService postService)
        {
            _postService = postService;
        }

        public IActionResult Results(string searchQuery)
        {
            var posts = _postService.GetFilteredPosts(searchQuery);

            var areNoResults = 
                (!string.IsNullOrEmpty(searchQuery) && !posts.Any());

            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.PostId,
                AuthorId = post.ApplicationUsers.Id,
                AuthorName = post.ApplicationUsers.UserName,
                AuthorRating = post.ApplicationUsers.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new SearchResultModel
            {
                Posts = postListings,
                SearchQuery = searchQuery,
                EmptySearchResults = areNoResults
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;

            return new ForumListingModel
            {
                Id = forum.ForumId,
                ImageUrl = forum.ImageUrl,
                Name = forum.Title,
                Descritpion = forum.Description
            };
        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new { searchQuery });
        }
    }
}

DevelopersForum/Views/Home/Index.cshtml
@model  DevelopersForum.ViewModels.Home.HomeIndexModel

<div class="container body-content">
    <div class="row frontPageSplash">
        <div class="col-md-6 frontPageLearn">
            <div class="frontPageHeading">Learn, Collaborate, Share Knowledge</div>
            <p class="frontPageSubHeading"> Developers Forum is the world's fastest growing coding forum</p>
            <div>
                <form asp-controller="Search" asp-action="Search" method="post">
                    <input asp-for="SearchQuery" type="text" class="homeSearch" placeholder="Search..." />
                </form>
            </div>
        </div>       
    </div>

    <div class="row frontPageContent">
        <h3 id="latestPosts">Latest Posts</h3>
        <table class="table table-hover" id="latestPostsTable">
            <tbody>
                @foreach (var post in Model.LatestPosts)
                {
                    <tr>
                        <td>
                            <div class="forumLogo" style="background-image: url(@post.Forum.ImageUrl);"></div>
                            <div class="postTitle">
                                <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                                    @post.Title
                                </a>
                            </div>
                            <div class="postSubTitle">
                                @if(post.RepliesCount == 1)
                                {
                                    <span>@post.RepliesCount Reply</span>
                                }
                                else if(post.RepliesCount == 0)
                                {
                                    <span>No Replies</span>
                                }
                                else
                                {
                                    <span>@post.RepliesCount Replies</span>
                                }
                                <span class="postUser">
                                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">
                                        @post.AuthorName
                                    </a>
                                </span>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>